server:
  port: 9001

spring:
 application:
   name: microservice-movie

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true

info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@

logging:
  level:
    fun.mytoys.ticket.movie.client.UserFeignClient: DEBUG

management:
  # 显示hystrix.stream
  endpoints:
    web:
      exposure:
        include: hystrix.stream

  # health 展示hystrix状态
  endpoint:
    health:
      show-details: always

