server:
  port: 2000

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: microservice-upload

  servlet:
    multipart:
      max-file-size: 2000MB
      max-request-size: 2500MB
