server:
  port: 3000

spring:
  application:
    name: microservice-gateway

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/






management:
  endpoints:
    web:
      exposure:
        include: routes

